/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project.design;

import java.text.SimpleDateFormat;
import java.util.Date;

/**
 *
 * @author 
 */
public class FirstPage extends javax.swing.JFrame {

    /**
     * Creates new form HomePage1
     */
    public FirstPage() {
        initComponents();
        setDate();
        setTime();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBakGround = new javax.swing.JPanel();
        labelTitle = new javax.swing.JLabel();
        panelManageStudent = new javax.swing.JPanel();
        labelManageStudentText = new javax.swing.JLabel();
        panelManageTeacherDetail = new javax.swing.JPanel();
        labelManageTeacherText = new javax.swing.JLabel();
        panelMarkAttendance = new javax.swing.JPanel();
        labelMarkAttendanceText = new javax.swing.JLabel();
        panelSettlePayment = new javax.swing.JPanel();
        labelSettlePaymentText = new javax.swing.JLabel();
        panelManageClass = new javax.swing.JPanel();
        labelManageClassText = new javax.swing.JLabel();
        panelManageSubject = new javax.swing.JPanel();
        labelManageSubjectText = new javax.swing.JLabel();
        panelManageGrade = new javax.swing.JPanel();
        labelManageGradeText = new javax.swing.JLabel();
        panelManageExam = new javax.swing.JPanel();
        labelManageExamText = new javax.swing.JLabel();
        panelReport = new javax.swing.JPanel();
        labelReportText = new javax.swing.JLabel();
        labelSetting = new javax.swing.JLabel();
        labelLogOut = new javax.swing.JLabel();
        labelTime = new javax.swing.JLabel();
        labelDate = new javax.swing.JLabel();
        labelMinimize = new javax.swing.JLabel();
        labelExit = new javax.swing.JLabel();
        separatorTitle = new javax.swing.JSeparator();
        labelBackGround = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        panelBakGround.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelTitle.setFont(new java.awt.Font("Times New Roman", 1, 50)); // NOI18N
        labelTitle.setForeground(new java.awt.Color(255, 51, 51));
        labelTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTitle.setText("DAKUNA EDUCATION CENTER");
        panelBakGround.add(labelTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 40, 820, 80));

        panelManageStudent.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        panelManageStudent.setOpaque(false);
        panelManageStudent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelManageStudentMouseClicked(evt);
            }
        });

        labelManageStudentText.setBackground(new java.awt.Color(204, 204, 255));
        labelManageStudentText.setFont(new java.awt.Font("Verdana", 1, 20)); // NOI18N
        labelManageStudentText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelManageStudentText.setText("Manage Student");
        labelManageStudentText.setOpaque(true);

        javax.swing.GroupLayout panelManageStudentLayout = new javax.swing.GroupLayout(panelManageStudent);
        panelManageStudent.setLayout(panelManageStudentLayout);
        panelManageStudentLayout.setHorizontalGroup(
            panelManageStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelManageStudentLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelManageStudentText, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelManageStudentLayout.setVerticalGroup(
            panelManageStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelManageStudentLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelManageStudentText, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelBakGround.add(panelManageStudent, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 240, 80));

        panelManageTeacherDetail.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        panelManageTeacherDetail.setOpaque(false);
        panelManageTeacherDetail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelManageTeacherDetailMouseClicked(evt);
            }
        });

        labelManageTeacherText.setBackground(new java.awt.Color(204, 204, 255));
        labelManageTeacherText.setFont(new java.awt.Font("Verdana", 1, 20)); // NOI18N
        labelManageTeacherText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelManageTeacherText.setText("Manage Teacher");
        labelManageTeacherText.setOpaque(true);

        javax.swing.GroupLayout panelManageTeacherDetailLayout = new javax.swing.GroupLayout(panelManageTeacherDetail);
        panelManageTeacherDetail.setLayout(panelManageTeacherDetailLayout);
        panelManageTeacherDetailLayout.setHorizontalGroup(
            panelManageTeacherDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelManageTeacherDetailLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelManageTeacherText, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelManageTeacherDetailLayout.setVerticalGroup(
            panelManageTeacherDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelManageTeacherDetailLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelManageTeacherText, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelBakGround.add(panelManageTeacherDetail, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 230, 240, 80));

        panelMarkAttendance.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        panelMarkAttendance.setOpaque(false);
        panelMarkAttendance.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelMarkAttendanceMouseClicked(evt);
            }
        });

        labelMarkAttendanceText.setBackground(new java.awt.Color(204, 204, 255));
        labelMarkAttendanceText.setFont(new java.awt.Font("Verdana", 1, 20)); // NOI18N
        labelMarkAttendanceText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelMarkAttendanceText.setText("Mark Attendance");
        labelMarkAttendanceText.setOpaque(true);

        javax.swing.GroupLayout panelMarkAttendanceLayout = new javax.swing.GroupLayout(panelMarkAttendance);
        panelMarkAttendance.setLayout(panelMarkAttendanceLayout);
        panelMarkAttendanceLayout.setHorizontalGroup(
            panelMarkAttendanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMarkAttendanceLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelMarkAttendanceText, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelMarkAttendanceLayout.setVerticalGroup(
            panelMarkAttendanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMarkAttendanceLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelMarkAttendanceText, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelBakGround.add(panelMarkAttendance, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 230, 240, 80));

        panelSettlePayment.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        panelSettlePayment.setOpaque(false);
        panelSettlePayment.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelSettlePaymentMouseClicked(evt);
            }
        });

        labelSettlePaymentText.setBackground(new java.awt.Color(204, 204, 255));
        labelSettlePaymentText.setFont(new java.awt.Font("Verdana", 1, 20)); // NOI18N
        labelSettlePaymentText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelSettlePaymentText.setText("Settle Payment");
        labelSettlePaymentText.setOpaque(true);

        javax.swing.GroupLayout panelSettlePaymentLayout = new javax.swing.GroupLayout(panelSettlePayment);
        panelSettlePayment.setLayout(panelSettlePaymentLayout);
        panelSettlePaymentLayout.setHorizontalGroup(
            panelSettlePaymentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSettlePaymentLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelSettlePaymentText, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelSettlePaymentLayout.setVerticalGroup(
            panelSettlePaymentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSettlePaymentLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelSettlePaymentText, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelBakGround.add(panelSettlePayment, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 230, 230, 80));

        panelManageClass.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51), 2));
        panelManageClass.setOpaque(false);
        panelManageClass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelManageClassMouseClicked(evt);
            }
        });

        labelManageClassText.setBackground(new java.awt.Color(204, 204, 255));
        labelManageClassText.setFont(new java.awt.Font("Verdana", 1, 20)); // NOI18N
        labelManageClassText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelManageClassText.setText("Manage Class");
        labelManageClassText.setOpaque(true);

        javax.swing.GroupLayout panelManageClassLayout = new javax.swing.GroupLayout(panelManageClass);
        panelManageClass.setLayout(panelManageClassLayout);
        panelManageClassLayout.setHorizontalGroup(
            panelManageClassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelManageClassLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelManageClassText, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelManageClassLayout.setVerticalGroup(
            panelManageClassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelManageClassLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelManageClassText, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelBakGround.add(panelManageClass, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 230, 230, 80));

        panelManageSubject.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        panelManageSubject.setOpaque(false);
        panelManageSubject.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelManageSubjectMouseClicked(evt);
            }
        });

        labelManageSubjectText.setBackground(new java.awt.Color(204, 204, 255));
        labelManageSubjectText.setFont(new java.awt.Font("Verdana", 1, 20)); // NOI18N
        labelManageSubjectText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelManageSubjectText.setText("Manage Subject");
        labelManageSubjectText.setOpaque(true);

        javax.swing.GroupLayout panelManageSubjectLayout = new javax.swing.GroupLayout(panelManageSubject);
        panelManageSubject.setLayout(panelManageSubjectLayout);
        panelManageSubjectLayout.setHorizontalGroup(
            panelManageSubjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelManageSubjectLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelManageSubjectText, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelManageSubjectLayout.setVerticalGroup(
            panelManageSubjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelManageSubjectLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelManageSubjectText, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelBakGround.add(panelManageSubject, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 340, 240, 80));

        panelManageGrade.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        panelManageGrade.setOpaque(false);
        panelManageGrade.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelManageGradeMouseClicked(evt);
            }
        });

        labelManageGradeText.setBackground(new java.awt.Color(204, 204, 255));
        labelManageGradeText.setFont(new java.awt.Font("Verdana", 1, 20)); // NOI18N
        labelManageGradeText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelManageGradeText.setText("Manage Grade");
        labelManageGradeText.setOpaque(true);

        javax.swing.GroupLayout panelManageGradeLayout = new javax.swing.GroupLayout(panelManageGrade);
        panelManageGrade.setLayout(panelManageGradeLayout);
        panelManageGradeLayout.setHorizontalGroup(
            panelManageGradeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelManageGradeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelManageGradeText, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelManageGradeLayout.setVerticalGroup(
            panelManageGradeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelManageGradeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelManageGradeText, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelBakGround.add(panelManageGrade, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 340, 240, 80));

        panelManageExam.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        panelManageExam.setOpaque(false);
        panelManageExam.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelManageExamMouseClicked(evt);
            }
        });

        labelManageExamText.setBackground(new java.awt.Color(204, 204, 255));
        labelManageExamText.setFont(new java.awt.Font("Verdana", 1, 20)); // NOI18N
        labelManageExamText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelManageExamText.setText("Manage Exam");
        labelManageExamText.setOpaque(true);

        javax.swing.GroupLayout panelManageExamLayout = new javax.swing.GroupLayout(panelManageExam);
        panelManageExam.setLayout(panelManageExamLayout);
        panelManageExamLayout.setHorizontalGroup(
            panelManageExamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelManageExamLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelManageExamText, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelManageExamLayout.setVerticalGroup(
            panelManageExamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelManageExamLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelManageExamText, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelBakGround.add(panelManageExam, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 340, 240, 80));

        panelReport.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        panelReport.setOpaque(false);
        panelReport.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelReportMouseClicked(evt);
            }
        });

        labelReportText.setBackground(new java.awt.Color(204, 204, 255));
        labelReportText.setFont(new java.awt.Font("Verdana", 1, 20)); // NOI18N
        labelReportText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelReportText.setText("Report");
        labelReportText.setOpaque(true);

        javax.swing.GroupLayout panelReportLayout = new javax.swing.GroupLayout(panelReport);
        panelReport.setLayout(panelReportLayout);
        panelReportLayout.setHorizontalGroup(
            panelReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelReportLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelReportText, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelReportLayout.setVerticalGroup(
            panelReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelReportLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelReportText, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelBakGround.add(panelReport, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 340, 230, 80));

        labelSetting.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        labelSetting.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelSetting.setText("Setting");
        labelSetting.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        labelSetting.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelSettingMouseClicked(evt);
            }
        });
        panelBakGround.add(labelSetting, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 690, 190, 40));

        labelLogOut.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        labelLogOut.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelLogOut.setText("Log Out");
        labelLogOut.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        labelLogOut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelLogOutMouseClicked(evt);
            }
        });
        panelBakGround.add(labelLogOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 690, 190, 40));

        labelTime.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        labelTime.setText("Time");
        panelBakGround.add(labelTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 100, 240, 47));

        labelDate.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        labelDate.setText("date");
        panelBakGround.add(labelDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 60, 240, 27));

        labelMinimize.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        labelMinimize.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelMinimize.setText("-");
        labelMinimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelMinimizeMouseClicked(evt);
            }
        });
        panelBakGround.add(labelMinimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(1280, 0, 40, 40));

        labelExit.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        labelExit.setForeground(new java.awt.Color(255, 0, 0));
        labelExit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelExit.setText("X");
        labelExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelExitMouseClicked(evt);
            }
        });
        panelBakGround.add(labelExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1320, 0, 50, 40));

        separatorTitle.setForeground(new java.awt.Color(0, 0, 0));
        panelBakGround.add(separatorTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 162, 1370, -1));

        labelBackGround.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/blue-background-images-10.jpg"))); // NOI18N
        panelBakGround.add(labelBackGround, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 770));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBakGround, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBakGround, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void labelExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelExitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_labelExitMouseClicked

    private void labelMinimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelMinimizeMouseClicked
        setState(ICONIFIED);
    }//GEN-LAST:event_labelMinimizeMouseClicked

    private void panelManageStudentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelManageStudentMouseClicked
        new ManageStudent().setVisible(true);
        dispose();
    }//GEN-LAST:event_panelManageStudentMouseClicked

    private void panelManageTeacherDetailMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelManageTeacherDetailMouseClicked
        new ManageTeacherDetail().setVisible(true);
        dispose();
    }//GEN-LAST:event_panelManageTeacherDetailMouseClicked

    private void panelMarkAttendanceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelMarkAttendanceMouseClicked
        new MarkAttendance().setVisible(true);
        dispose();
    }//GEN-LAST:event_panelMarkAttendanceMouseClicked

    private void panelSettlePaymentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelSettlePaymentMouseClicked
        new SettlePayment().setVisible(true);
        dispose();
    }//GEN-LAST:event_panelSettlePaymentMouseClicked

    private void panelManageClassMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelManageClassMouseClicked
        new ManageClass().setVisible(true);
        dispose();
    }//GEN-LAST:event_panelManageClassMouseClicked

    private void panelManageSubjectMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelManageSubjectMouseClicked
        new ManageSubject().setVisible(true);
        dispose();
    }//GEN-LAST:event_panelManageSubjectMouseClicked

    private void panelManageGradeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelManageGradeMouseClicked
        new ManageGrade().setVisible(true);
        dispose();
    }//GEN-LAST:event_panelManageGradeMouseClicked

    private void panelManageExamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelManageExamMouseClicked
        new ManageExam().setVisible(true);
        dispose();
    }//GEN-LAST:event_panelManageExamMouseClicked

    private void panelReportMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelReportMouseClicked
        new Report().setVisible(true);
        dispose();
    }//GEN-LAST:event_panelReportMouseClicked

    private void labelLogOutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelLogOutMouseClicked
        System.exit(0);
    }//GEN-LAST:event_labelLogOutMouseClicked

    private void labelSettingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelSettingMouseClicked
        new ChangePassword().setVisible(true);
    }//GEN-LAST:event_labelSettingMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FirstPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FirstPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FirstPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FirstPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FirstPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel labelBackGround;
    private javax.swing.JLabel labelDate;
    private javax.swing.JLabel labelExit;
    private javax.swing.JLabel labelLogOut;
    private javax.swing.JLabel labelManageClassText;
    private javax.swing.JLabel labelManageExamText;
    private javax.swing.JLabel labelManageGradeText;
    private javax.swing.JLabel labelManageStudentText;
    private javax.swing.JLabel labelManageSubjectText;
    private javax.swing.JLabel labelManageTeacherText;
    private javax.swing.JLabel labelMarkAttendanceText;
    private javax.swing.JLabel labelMinimize;
    private javax.swing.JLabel labelReportText;
    private javax.swing.JLabel labelSetting;
    private javax.swing.JLabel labelSettlePaymentText;
    private javax.swing.JLabel labelTime;
    private javax.swing.JLabel labelTitle;
    private javax.swing.JPanel panelBakGround;
    private javax.swing.JPanel panelManageClass;
    private javax.swing.JPanel panelManageExam;
    private javax.swing.JPanel panelManageGrade;
    private javax.swing.JPanel panelManageStudent;
    private javax.swing.JPanel panelManageSubject;
    private javax.swing.JPanel panelManageTeacherDetail;
    private javax.swing.JPanel panelMarkAttendance;
    private javax.swing.JPanel panelReport;
    private javax.swing.JPanel panelSettlePayment;
    private javax.swing.JSeparator separatorTitle;
    // End of variables declaration//GEN-END:variables

    private void setDate() {
        SimpleDateFormat dateFormat=new SimpleDateFormat("yyyy-MM-dd");
        String date=dateFormat.format(new Date());
        labelDate.setText(date);
    }

    private void setTime() {
        new Thread(){
            public void run(){
                while (true) {                    
                    SimpleDateFormat dateFormat=new SimpleDateFormat("hh:mm:ss aa");
                    labelTime.setText(dateFormat.format(new Date()));
                }
            }
        }.start();
    }
}
