/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project.design;

import java.awt.TextField;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import project.controller.GenerateIdController;
import project.controller.TeacherController;
import project.controller.ValidationController;
import project.model.Teacher;

/**
 *
 * @author 
 */
public class ManageTeacherDetail extends javax.swing.JFrame {

    /**
     * Creates new form ManageTeacherDetail
     */
    public ManageTeacherDetail() {
        initComponents();
        generateTeacherId();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupNIC = new javax.swing.ButtonGroup();
        panelBackGround = new javax.swing.JPanel();
        labelTitle = new javax.swing.JLabel();
        panelAddTeacher = new javax.swing.JPanel();
        labelTeacherId = new javax.swing.JLabel();
        labelTeacherName = new javax.swing.JLabel();
        labelAddress = new javax.swing.JLabel();
        labelNIC = new javax.swing.JLabel();
        labelTeleNo = new javax.swing.JLabel();
        radioButtonNIC9 = new javax.swing.JRadioButton();
        radioButtonNIC12 = new javax.swing.JRadioButton();
        textTeacherId = new javax.swing.JTextField();
        textTeacherName = new javax.swing.JTextField();
        textAddress = new javax.swing.JTextField();
        textNIC = new javax.swing.JTextField();
        labelRegisterTeacher = new javax.swing.JLabel();
        labelClear = new javax.swing.JLabel();
        textTeleNo = new javax.swing.JTextField();
        panelSearchTeacher = new javax.swing.JPanel();
        labelTeacherIdInDetail = new javax.swing.JLabel();
        textTeacherIdInDetail = new javax.swing.JTextField();
        labelTeacherNameInDetail = new javax.swing.JLabel();
        labelAddressInDetail = new javax.swing.JLabel();
        labelNICInDetail = new javax.swing.JLabel();
        labelTeleNoInDetail = new javax.swing.JLabel();
        textTeacherNameInDetail = new javax.swing.JTextField();
        textAddressInDetail = new javax.swing.JTextField();
        textNICInDetail = new javax.swing.JTextField();
        textTeleNoInDetail = new javax.swing.JTextField();
        labelModifyTeacherDetail = new javax.swing.JLabel();
        labelRemoveTeacherDetail = new javax.swing.JLabel();
        textModifyTeacherNameInDetail = new javax.swing.JTextField();
        labelDescribeModifyName = new javax.swing.JLabel();
        labelBackToFirstPage = new javax.swing.JLabel();
        labelBackGround = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        panelBackGround.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelTitle.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        labelTitle.setForeground(new java.awt.Color(255, 0, 0));
        labelTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTitle.setText("Manage Teacher's Detail");
        panelBackGround.add(labelTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 30, 680, 60));

        panelAddTeacher.setBackground(new java.awt.Color(153, 153, 255));
        panelAddTeacher.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Add Teacher", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 24), new java.awt.Color(0, 0, 102))); // NOI18N

        labelTeacherId.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        labelTeacherId.setText("Teacher Id");

        labelTeacherName.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        labelTeacherName.setText("Teacher Name");

        labelAddress.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        labelAddress.setText("Address");

        labelNIC.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        labelNIC.setText("NIC");

        labelTeleNo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        labelTeleNo.setText("Tele. No");

        buttonGroupNIC.add(radioButtonNIC9);
        radioButtonNIC9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        radioButtonNIC9.setText("Number of NIC - 9");
        radioButtonNIC9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioButtonNIC9ActionPerformed(evt);
            }
        });

        buttonGroupNIC.add(radioButtonNIC12);
        radioButtonNIC12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        radioButtonNIC12.setText("Number of NIC - 12");
        radioButtonNIC12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioButtonNIC12ActionPerformed(evt);
            }
        });

        textTeacherId.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        textTeacherId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textTeacherIdActionPerformed(evt);
            }
        });

        textTeacherName.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        textTeacherName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textTeacherNameActionPerformed(evt);
            }
        });

        textAddress.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        textAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textAddressActionPerformed(evt);
            }
        });

        textNIC.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        textNIC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textNICActionPerformed(evt);
            }
        });
        textNIC.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                textNICKeyReleased(evt);
            }
        });

        labelRegisterTeacher.setBackground(new java.awt.Color(255, 0, 0));
        labelRegisterTeacher.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        labelRegisterTeacher.setForeground(new java.awt.Color(255, 255, 255));
        labelRegisterTeacher.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelRegisterTeacher.setText("Register Teacher");
        labelRegisterTeacher.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1), javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0))));
        labelRegisterTeacher.setOpaque(true);
        labelRegisterTeacher.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelRegisterTeacherMouseClicked(evt);
            }
        });

        labelClear.setBackground(new java.awt.Color(255, 0, 0));
        labelClear.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        labelClear.setForeground(new java.awt.Color(255, 255, 255));
        labelClear.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelClear.setText("Clear");
        labelClear.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1), javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0))));
        labelClear.setOpaque(true);
        labelClear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelClearMouseClicked(evt);
            }
        });

        textTeleNo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        textTeleNo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                textTeleNoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textTeleNoKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout panelAddTeacherLayout = new javax.swing.GroupLayout(panelAddTeacher);
        panelAddTeacher.setLayout(panelAddTeacherLayout);
        panelAddTeacherLayout.setHorizontalGroup(
            panelAddTeacherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAddTeacherLayout.createSequentialGroup()
                .addGroup(panelAddTeacherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelAddTeacherLayout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(labelRegisterTeacher, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55)
                        .addComponent(labelClear, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelAddTeacherLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(panelAddTeacherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(labelTeacherName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelTeacherId, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelAddress, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelNIC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelTeleNo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(panelAddTeacherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelAddTeacherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(textTeleNo, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(textNIC, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE))
                            .addGroup(panelAddTeacherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(textTeacherId, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(textTeacherName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE))))
                    .addGroup(panelAddTeacherLayout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(radioButtonNIC9)
                        .addGap(36, 36, 36)
                        .addComponent(radioButtonNIC12)))
                .addContainerGap(79, Short.MAX_VALUE))
        );
        panelAddTeacherLayout.setVerticalGroup(
            panelAddTeacherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAddTeacherLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(panelAddTeacherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelTeacherId, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textTeacherId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelAddTeacherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTeacherName, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textTeacherName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelAddTeacherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(panelAddTeacherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioButtonNIC9)
                    .addComponent(radioButtonNIC12))
                .addGap(31, 31, 31)
                .addGroup(panelAddTeacherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNIC, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textNIC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelAddTeacherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelTeleNo, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textTeleNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(97, 97, 97)
                .addGroup(panelAddTeacherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelRegisterTeacher, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelClear, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(68, Short.MAX_VALUE))
        );

        panelBackGround.add(panelAddTeacher, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 580, 560));

        panelSearchTeacher.setBackground(new java.awt.Color(153, 153, 255));
        panelSearchTeacher.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Teacher's Detail", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 24), new java.awt.Color(0, 0, 102))); // NOI18N

        labelTeacherIdInDetail.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        labelTeacherIdInDetail.setText("Teacher Id");

        textTeacherIdInDetail.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        labelTeacherNameInDetail.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        labelTeacherNameInDetail.setText("Teacher Name");

        labelAddressInDetail.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        labelAddressInDetail.setText("Address");

        labelNICInDetail.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        labelNICInDetail.setText("NIC");

        labelTeleNoInDetail.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        labelTeleNoInDetail.setText("Tele. No");

        textTeacherNameInDetail.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        textTeacherNameInDetail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                textTeacherNameInDetailKeyReleased(evt);
            }
        });

        textAddressInDetail.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        textNICInDetail.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        textTeleNoInDetail.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        labelModifyTeacherDetail.setBackground(new java.awt.Color(255, 0, 0));
        labelModifyTeacherDetail.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        labelModifyTeacherDetail.setForeground(new java.awt.Color(255, 255, 255));
        labelModifyTeacherDetail.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelModifyTeacherDetail.setText("Modify Teacher Detail");
        labelModifyTeacherDetail.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1), javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0))));
        labelModifyTeacherDetail.setOpaque(true);
        labelModifyTeacherDetail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelModifyTeacherDetailMouseClicked(evt);
            }
        });

        labelRemoveTeacherDetail.setBackground(new java.awt.Color(255, 0, 0));
        labelRemoveTeacherDetail.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        labelRemoveTeacherDetail.setForeground(new java.awt.Color(255, 255, 255));
        labelRemoveTeacherDetail.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelRemoveTeacherDetail.setText("Remove Teacher Detail");
        labelRemoveTeacherDetail.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1), javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0))));
        labelRemoveTeacherDetail.setOpaque(true);
        labelRemoveTeacherDetail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelRemoveTeacherDetailMouseClicked(evt);
            }
        });

        textModifyTeacherNameInDetail.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        textModifyTeacherNameInDetail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                textModifyTeacherNameInDetailKeyReleased(evt);
            }
        });

        labelDescribeModifyName.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelDescribeModifyName.setText("If you want to modify teacher name, type new name below text field.");

        javax.swing.GroupLayout panelSearchTeacherLayout = new javax.swing.GroupLayout(panelSearchTeacher);
        panelSearchTeacher.setLayout(panelSearchTeacherLayout);
        panelSearchTeacherLayout.setHorizontalGroup(
            panelSearchTeacherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSearchTeacherLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(panelSearchTeacherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelSearchTeacherLayout.createSequentialGroup()
                        .addComponent(labelModifyTeacherDetail, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(labelRemoveTeacherDetail, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSearchTeacherLayout.createSequentialGroup()
                        .addGroup(panelSearchTeacherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labelTeacherIdInDetail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelAddressInDetail, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelNICInDetail, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelTeleNoInDetail, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelTeacherNameInDetail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(panelSearchTeacherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textAddressInDetail, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelSearchTeacherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(textTeacherIdInDetail, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(textTeacherNameInDetail, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE)
                                .addComponent(textModifyTeacherNameInDetail, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE))
                            .addGroup(panelSearchTeacherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(textTeleNoInDetail, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(textNICInDetail, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)))
                        .addGap(43, 43, 43))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSearchTeacherLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelDescribeModifyName)
                .addGap(31, 31, 31))
        );
        panelSearchTeacherLayout.setVerticalGroup(
            panelSearchTeacherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSearchTeacherLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(panelSearchTeacherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTeacherNameInDetail, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textTeacherNameInDetail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelDescribeModifyName)
                .addGap(9, 9, 9)
                .addComponent(textModifyTeacherNameInDetail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelSearchTeacherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTeacherIdInDetail, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textTeacherIdInDetail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelSearchTeacherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelAddressInDetail, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textAddressInDetail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelSearchTeacherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textNICInDetail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelNICInDetail, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelSearchTeacherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTeleNoInDetail, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textTeleNoInDetail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(78, 78, 78)
                .addGroup(panelSearchTeacherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelModifyTeacherDetail, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelRemoveTeacherDetail, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(101, Short.MAX_VALUE))
        );

        panelBackGround.add(panelSearchTeacher, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 130, 610, 560));

        labelBackToFirstPage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gif/home-animated-blue-1.gif"))); // NOI18N
        labelBackToFirstPage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelBackToFirstPageMouseClicked(evt);
            }
        });
        panelBackGround.add(labelBackToFirstPage, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 90, 90));

        labelBackGround.setBackground(new java.awt.Color(0, 0, 153));
        labelBackGround.setOpaque(true);
        panelBackGround.add(labelBackGround, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 770));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBackGround, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBackGround, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textTeacherIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textTeacherIdActionPerformed
        textTeacherName.requestFocus();
    }//GEN-LAST:event_textTeacherIdActionPerformed

    private void textTeacherNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textTeacherNameActionPerformed
        textAddress.requestFocus();
    }//GEN-LAST:event_textTeacherNameActionPerformed

    private void textAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textAddressActionPerformed
        radioButtonNIC9.requestFocus();
    }//GEN-LAST:event_textAddressActionPerformed

    private void radioButtonNIC12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioButtonNIC12ActionPerformed
        textNIC.requestFocus();
    }//GEN-LAST:event_radioButtonNIC12ActionPerformed

    private void radioButtonNIC9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioButtonNIC9ActionPerformed
        textNIC.requestFocus();
    }//GEN-LAST:event_radioButtonNIC9ActionPerformed

    private void textNICActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textNICActionPerformed
        textTeleNo.requestFocus();
    }//GEN-LAST:event_textNICActionPerformed

    private void textNICKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textNICKeyReleased
        String nic=textNIC.getText();
        nic=nic.replaceAll("[\\D&&[^v]&&[^x]]", "");
        textNIC.setText(nic);
        boolean nic9=radioButtonNIC9.isSelected();
        if(nic9==true){
            clickRadioButtonNIC9();
        }
        boolean nic12=radioButtonNIC12.isSelected();
        if(nic12==true){
            clickRadioButtonNIC12();
        }
    }//GEN-LAST:event_textNICKeyReleased

    private void labelRegisterTeacherMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelRegisterTeacherMouseClicked
        addTeacher();
    }//GEN-LAST:event_labelRegisterTeacherMouseClicked

    private void textTeacherNameInDetailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textTeacherNameInDetailKeyReleased
        searchTeacher();
    }//GEN-LAST:event_textTeacherNameInDetailKeyReleased

    private void labelModifyTeacherDetailMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelModifyTeacherDetailMouseClicked
        modifyTeacherDetail();
    }//GEN-LAST:event_labelModifyTeacherDetailMouseClicked

    private void labelRemoveTeacherDetailMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelRemoveTeacherDetailMouseClicked
        removeTeacherDetail();
    }//GEN-LAST:event_labelRemoveTeacherDetailMouseClicked

    private void labelClearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelClearMouseClicked
        clearTextField();
    }//GEN-LAST:event_labelClearMouseClicked

    private void textTeleNoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textTeleNoKeyTyped
        ValidationController.NumbersOnlyTextFiled(evt);
    }//GEN-LAST:event_textTeleNoKeyTyped

    private void labelBackToFirstPageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelBackToFirstPageMouseClicked
        new FirstPage().setVisible(true);
        dispose();
    }//GEN-LAST:event_labelBackToFirstPageMouseClicked

    private void textModifyTeacherNameInDetailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textModifyTeacherNameInDetailKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_textModifyTeacherNameInDetailKeyReleased

    private void textTeleNoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textTeleNoKeyReleased
        //
    }//GEN-LAST:event_textTeleNoKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageTeacherDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageTeacherDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageTeacherDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageTeacherDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageTeacherDetail().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupNIC;
    private javax.swing.JLabel labelAddress;
    private javax.swing.JLabel labelAddressInDetail;
    private javax.swing.JLabel labelBackGround;
    private javax.swing.JLabel labelBackToFirstPage;
    private javax.swing.JLabel labelClear;
    private javax.swing.JLabel labelDescribeModifyName;
    private javax.swing.JLabel labelModifyTeacherDetail;
    private javax.swing.JLabel labelNIC;
    private javax.swing.JLabel labelNICInDetail;
    private javax.swing.JLabel labelRegisterTeacher;
    private javax.swing.JLabel labelRemoveTeacherDetail;
    private javax.swing.JLabel labelTeacherId;
    private javax.swing.JLabel labelTeacherIdInDetail;
    private javax.swing.JLabel labelTeacherName;
    private javax.swing.JLabel labelTeacherNameInDetail;
    private javax.swing.JLabel labelTeleNo;
    private javax.swing.JLabel labelTeleNoInDetail;
    private javax.swing.JLabel labelTitle;
    private javax.swing.JPanel panelAddTeacher;
    private javax.swing.JPanel panelBackGround;
    private javax.swing.JPanel panelSearchTeacher;
    private javax.swing.JRadioButton radioButtonNIC12;
    private javax.swing.JRadioButton radioButtonNIC9;
    private javax.swing.JTextField textAddress;
    private javax.swing.JTextField textAddressInDetail;
    private javax.swing.JTextField textModifyTeacherNameInDetail;
    private javax.swing.JTextField textNIC;
    private javax.swing.JTextField textNICInDetail;
    private javax.swing.JTextField textTeacherId;
    private javax.swing.JTextField textTeacherIdInDetail;
    private javax.swing.JTextField textTeacherName;
    private javax.swing.JTextField textTeacherNameInDetail;
    private javax.swing.JTextField textTeleNo;
    private javax.swing.JTextField textTeleNoInDetail;
    // End of variables declaration//GEN-END:variables

    private void clickRadioButtonNIC9() {
        int index=textNIC.getText().length();
        if(index==9){
            String nic=textNIC.getText();
            textNIC.setText(nic+"v");
            textTeleNo.requestFocus();
        }
    }

    private void addTeacher() {
        if (ckeckAllTextField()) {
            Teacher teacher=new Teacher(textTeacherId.getText(), textTeacherName.getText(), textAddress.getText(), textNIC.getText(), Integer.parseInt(textTeleNo.getText()));
            try {
                boolean isAdded = TeacherController.addTeacher(teacher);;            
                if (isAdded) {
                    JOptionPane.showMessageDialog(this, "Added success!");
                } else {
                    JOptionPane.showMessageDialog(this, "Added Fail!");
                }            
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(ManageTeacherDetail.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, "TID is duplicate!\nPlease enter correct TID...!");
            } 
        }else{
            JOptionPane.showMessageDialog(this, "Check whether you have fill all text field");
        }
        
    }

    private void searchTeacher() {
        String name=textTeacherNameInDetail.getText();
        int index=name.length();
        
        try {
            Teacher teacher=TeacherController.searchTeacherByName(name);
            if (teacher!=null) {
                textTeacherNameInDetail.setText(teacher.getName());
                textTeacherNameInDetail.select(index, 20);
                textModifyTeacherNameInDetail.setText(teacher.getName());
                textTeacherIdInDetail.setText(teacher.getTID());
                textAddressInDetail.setText(teacher.getAddress());
                textNICInDetail.setText(teacher.getNIC());
                textTeleNoInDetail.setText(Integer.toString(teacher.getTeleNo()));
            }else{                              
                textTeacherIdInDetail.setText("");
                textAddressInDetail.setText("");
                textNICInDetail.setText("");
                textTeleNoInDetail.setText("");
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ManageTeacherDetail.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(ManageTeacherDetail.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void clickRadioButtonNIC12() {
        int index=textNIC.getText().length();
        if(index==12){
            String nic=textNIC.getText();
            textNIC.setText(nic+"x");
            textTeleNo.requestFocus();
        }
    }

    private void modifyTeacherDetail() {
        Teacher teacher=new Teacher(textTeacherIdInDetail.getText(), textModifyTeacherNameInDetail.getText(), textAddressInDetail.getText(), textNICInDetail.getText(), Integer.parseInt(textTeleNoInDetail.getText()));
        try {
            boolean isUpdated=TeacherController.updateTeacher(teacher);
            if (isUpdated) {
                JOptionPane.showMessageDialog(this, "Updated success!");
            } else {
                JOptionPane.showMessageDialog(this, "Updated Fail!");
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ManageTeacherDetail.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(ManageTeacherDetail.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void removeTeacherDetail() {
        String tid=textTeacherIdInDetail.getText();
        try {
            boolean isDeleted=TeacherController.deleteTeacher(tid);
            if (isDeleted) {
                JOptionPane.showMessageDialog(this, "Deleted success!");
            } else {
                JOptionPane.showMessageDialog(this, "Deleted Fail!");
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ManageTeacherDetail.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(ManageTeacherDetail.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void clearTextField() {
        generateTeacherId();
        textTeacherName.setText("");
        textAddress.setText("");
        textNIC.setText("");
        textTeleNo.setText("");
        
    }

    private boolean ckeckAllTextField() {
        boolean fillTeacherId=textTeacherId.getText().isEmpty();
        boolean fillTeacherName=textTeacherName.getText().isEmpty();
        boolean fillAddress=textAddress.getText().isEmpty();
        boolean fillNIC=textNIC.getText().isEmpty();
        boolean fillTeleNo=textTeleNo.getText().isEmpty();
        if (fillTeacherId || fillTeacherName || fillAddress || fillNIC || fillTeleNo) {
            return false;
        } else {
            return true;
        }
    }

    private void generateTeacherId() {
        String teacherId=null;
        try {
            teacherId=GenerateIdController.lastTableId("TID", "Teacher");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ManageTeacherDetail.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(ManageTeacherDetail.class.getName()).log(Level.SEVERE, null, ex);
        }
        if (teacherId!=null) {
            int idLength=teacherId.length();
            String idNumber=teacherId.substring(1, idLength);
            int idNumberInteger=Integer.parseInt(idNumber);
            int nextNumber=idNumberInteger+1;
            if (nextNumber<10) {
                textTeacherId.setText("t00"+nextNumber);
            }
            if (nextNumber>=10 & nextNumber<100) {
                textTeacherId.setText("t0"+nextNumber);
            }
            if (nextNumber>=100) {
                textTeacherId.setText("t"+nextNumber);
            }
        } else {
            textTeacherId.setText("t001");
        }
    }
}
