/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project.design;

/**
 *
 * @author Lahiru Sandeepa
 */
public class Report extends javax.swing.JFrame {

    /**
     * Creates new form Report
     */
    public Report() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBackGround = new javax.swing.JPanel();
        labelTitle = new javax.swing.JLabel();
        labelReportOfClass = new javax.swing.JLabel();
        labelReportOfStudent = new javax.swing.JLabel();
        labelReportOfTeacher = new javax.swing.JLabel();
        panelDisplayChange = new javax.swing.JPanel();
        labelReportOfExam = new javax.swing.JLabel();
        labelBackToFirstPage = new javax.swing.JLabel();
        labelBackGround = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        panelBackGround.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelTitle.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        labelTitle.setForeground(new java.awt.Color(255, 0, 0));
        labelTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTitle.setText("Report");
        panelBackGround.add(labelTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 10, 550, 70));

        labelReportOfClass.setBackground(new java.awt.Color(204, 0, 0));
        labelReportOfClass.setFont(new java.awt.Font("Verdana", 1, 20)); // NOI18N
        labelReportOfClass.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelReportOfClass.setText("Report of Class");
        labelReportOfClass.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 0, 0), new java.awt.Color(153, 0, 0)), javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255))));
        labelReportOfClass.setOpaque(true);
        labelReportOfClass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelReportOfClassMouseClicked(evt);
            }
        });
        panelBackGround.add(labelReportOfClass, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 210, 60));

        labelReportOfStudent.setBackground(new java.awt.Color(204, 0, 0));
        labelReportOfStudent.setFont(new java.awt.Font("Verdana", 1, 20)); // NOI18N
        labelReportOfStudent.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelReportOfStudent.setText("Report of Student");
        labelReportOfStudent.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 0, 0), new java.awt.Color(153, 0, 0)), javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255))));
        labelReportOfStudent.setOpaque(true);
        labelReportOfStudent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelReportOfStudentMouseClicked(evt);
            }
        });
        panelBackGround.add(labelReportOfStudent, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 210, 60));

        labelReportOfTeacher.setBackground(new java.awt.Color(204, 0, 0));
        labelReportOfTeacher.setFont(new java.awt.Font("Verdana", 1, 20)); // NOI18N
        labelReportOfTeacher.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelReportOfTeacher.setText("Report of Teacher");
        labelReportOfTeacher.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 0, 0), new java.awt.Color(153, 0, 0)), javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255))));
        labelReportOfTeacher.setOpaque(true);
        labelReportOfTeacher.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelReportOfTeacherMouseClicked(evt);
            }
        });
        panelBackGround.add(labelReportOfTeacher, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 210, 60));

        panelDisplayChange.setBackground(new java.awt.Color(153, 153, 255));
        panelDisplayChange.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        panelDisplayChange.setPreferredSize(new java.awt.Dimension(1100, 600));

        javax.swing.GroupLayout panelDisplayChangeLayout = new javax.swing.GroupLayout(panelDisplayChange);
        panelDisplayChange.setLayout(panelDisplayChangeLayout);
        panelDisplayChangeLayout.setHorizontalGroup(
            panelDisplayChangeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1096, Short.MAX_VALUE)
        );
        panelDisplayChangeLayout.setVerticalGroup(
            panelDisplayChangeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 586, Short.MAX_VALUE)
        );

        panelBackGround.add(panelDisplayChange, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 120, 1100, 590));

        labelReportOfExam.setBackground(new java.awt.Color(204, 0, 0));
        labelReportOfExam.setFont(new java.awt.Font("Verdana", 1, 20)); // NOI18N
        labelReportOfExam.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelReportOfExam.setText("Report of Exam");
        labelReportOfExam.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 0, 0), new java.awt.Color(153, 0, 0)), javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255))));
        labelReportOfExam.setOpaque(true);
        labelReportOfExam.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelReportOfExamMouseClicked(evt);
            }
        });
        panelBackGround.add(labelReportOfExam, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, 210, 60));

        labelBackToFirstPage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gif/home-animated-blue-1.gif"))); // NOI18N
        labelBackToFirstPage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelBackToFirstPageMouseClicked(evt);
            }
        });
        panelBackGround.add(labelBackToFirstPage, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 90, 90));

        labelBackGround.setBackground(new java.awt.Color(0, 0, 153));
        labelBackGround.setOpaque(true);
        panelBackGround.add(labelBackGround, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 770));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBackGround, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBackGround, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void labelReportOfClassMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelReportOfClassMouseClicked
        panelDisplayChange.removeAll();
        ReportOfClass reportOfClass=new ReportOfClass();
        reportOfClass.setSize(panelDisplayChange.getSize());
        panelDisplayChange.add(reportOfClass);
        panelDisplayChange.repaint();
        panelDisplayChange.revalidate();
        labelTitle.setText("Report Of Class");
    }//GEN-LAST:event_labelReportOfClassMouseClicked

    private void labelReportOfStudentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelReportOfStudentMouseClicked
        panelDisplayChange.removeAll();
        ReportOfStudent reportOfStudent=new ReportOfStudent();
        reportOfStudent.setSize(panelDisplayChange.getSize());
        panelDisplayChange.add(reportOfStudent);
        panelDisplayChange.repaint();
        panelDisplayChange.revalidate();
        labelTitle.setText("Report Of Student");
    }//GEN-LAST:event_labelReportOfStudentMouseClicked

    private void labelReportOfTeacherMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelReportOfTeacherMouseClicked
        panelDisplayChange.removeAll();
        ReportOfTeacher reportOfTeacher=new ReportOfTeacher();
        reportOfTeacher.setSize(panelDisplayChange.getSize());
        panelDisplayChange.add(reportOfTeacher);
        panelDisplayChange.repaint();
        panelDisplayChange.revalidate();
        labelTitle.setText("Report Of Teacher");
    }//GEN-LAST:event_labelReportOfTeacherMouseClicked

    private void labelReportOfExamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelReportOfExamMouseClicked
        panelDisplayChange.removeAll();
        ReportOfExam reportOfExam=new ReportOfExam();
        reportOfExam.setSize(panelDisplayChange.getSize());
        panelDisplayChange.add(reportOfExam);
        panelDisplayChange.repaint();
        panelDisplayChange.revalidate();
        labelTitle.setText("Report Of Exam");
    }//GEN-LAST:event_labelReportOfExamMouseClicked

    private void labelBackToFirstPageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelBackToFirstPageMouseClicked
        new FirstPage().setVisible(true);
        dispose();
    }//GEN-LAST:event_labelBackToFirstPageMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Report().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel labelBackGround;
    private javax.swing.JLabel labelBackToFirstPage;
    private javax.swing.JLabel labelReportOfClass;
    private javax.swing.JLabel labelReportOfExam;
    private javax.swing.JLabel labelReportOfStudent;
    private javax.swing.JLabel labelReportOfTeacher;
    private javax.swing.JLabel labelTitle;
    private javax.swing.JPanel panelBackGround;
    private javax.swing.JPanel panelDisplayChange;
    // End of variables declaration//GEN-END:variables
}
